name: Android CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: List output APK files
        run: find . -name "*.apk" | xargs ls -lh

      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa srv01.letscode.it >> ~/.ssh/known_hosts
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; '

      - name: Extract version name
        run: |
          VERSION_NAME=$(grep 'versionName' app/build.gradle.kts | awk '{print $3}' | tr -d "\"")
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Copy APK to the server
        run: |
          scp app/build/outputs/apk/debug/app-debug.apk fadeusz@srv01.letscode.it:/home/fadeusz/domains/download.simply-connect.ovh/public/app-debug.apk
          scp app/build/outputs/apk/debug/app-debug.apk fadeusz@srv01.letscode.it:/home/fadeusz/domains/download.simply-connect.ovh/public/app-debug-${{ env.VERSION_NAME }}.apk
      
