name: Android CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Verify Sentry configuration
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli send-event --message "Testing Sentry integration from GitHub Actions"

      - name: List output APK files
        run: find . -name "*.apk" | xargs ls -lh

      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa srv01.letscode.it >> ~/.ssh/known_hosts
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; '

      - name: Copy APK to the server
        run: scp app/build/outputs/apk/debug/app-debug.apk fadeusz@srv01.letscode.it:/home/fadeusz/domains/download.simply-connect.ovh/public
