name: Android CI

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Add SSH key
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa srv01.letscode.it >> ~/.ssh/known_hosts
          ssh-agent bash -c 'ssh-add ~/.ssh/id_rsa; '

      - name: Copy APK to the server
        run: scp app/build/outputs/apk/release/app-release.apk fadeusz@srv01.letscode.it:/home/fadeusz/domains/srv01.letscode.it/public