name: Verify Sentry Configuration

on: [push]

jobs:
  verify-sentry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash

      - name: Verify Sentry configuration
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: |
          sentry-cli send-event --message "Testing Sentry integration from GitHub Actions"
